name: CI

on: [push]

jobs:
  pylama:
    runs-on: ubuntu-22.04
   
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install tox
      run: pip install tox
    - name: Run linting with tox
      run: tox -e lint
        
  mypy:
    runs-on: ubuntu-22.04
   
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install tox
      run: pip install tox
    - name: Run type checks with tox
      run: tox -e static
        
  unittest:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install tox
      run: pip install tox
    - name: Run unit tests with tox
      run: tox -e unit
